-- Demo: the shared skill_library for Hermes agents, as created through MCP on 2026-09-08/09.
-- Public read for anon/authenticated; anon INSERT policy is included as originally written,
-- drop it if only MCP clients should publish.
-- migration 20260908231339 create_skill_library
create table if not exists public.skill_library (   id uuid primary key default gen_random_uuid(),   slug text not null,   name text not null,   description text not null default '',   skill_md text not null,   version text not null default '1.0.0',   author_name text not null default '',   license text not null default 'MIT',   tags text[] not null default '{}',   visibility text not null default 'public' check (visibility in ('public', 'unlisted', 'private')),   status text not null default 'draft' check (status in ('draft', 'published', 'archived')),   metadata jsonb not null default '{}'::jsonb,   downloads integer not null default 0 check (downloads >= 0),   created_at timestamptz not null default now(),   updated_at timestamptz not null default now(),   unique (slug, version) );  create index if not exists skill_library_status_visibility_idx   on public.skill_library (status, visibility);  create index if not exists skill_library_tags_idx   on public.skill_library using gin (tags);  comment on table public.skill_library is 'Shared library of Hermes Agent skills'; comment on column public.skill_library.skill_md is 'The complete SKILL.md content';

-- migration 20260908231446 make_skill_library_public
alter table public.skill_library enable row level security;  alter table public.skill_library   alter column visibility set default 'public',   alter column status set default 'published';  drop policy if exists skill_library_public_read on public.skill_library; create policy skill_library_public_read   on public.skill_library   for select   to anon, authenticated   using (visibility = 'public' and status = 'published');  drop policy if exists skill_library_public_insert on public.skill_library; create policy skill_library_public_insert   on public.skill_library   for insert   to anon, authenticated   with check (visibility = 'public' and status = 'published');

-- migration 20260908232235 add_skill_library_search_v2
create index if not exists skill_library_name_lower_idx   on public.skill_library (lower(name));  create index if not exists skill_library_slug_lower_idx   on public.skill_library (lower(slug));  create or replace function public.search_public_skills(search_query text, result_limit integer default 20) returns setof public.skill_library language sql stable security invoker set search_path = public as $$   select s.*   from public.skill_library s   where s.visibility = 'public'     and s.status = 'published'     and (       nullif(trim(search_query), '') is null       or s.name ilike '%' || search_query || '%'       or s.slug ilike '%' || search_query || '%'       or s.description ilike '%' || search_query || '%'       or exists (         select 1 from unnest(s.tags) tag         where tag ilike '%' || search_query || '%'       )     )   order by s.updated_at desc   limit greatest(1, least(result_limit, 100)); $$;  grant execute on function public.search_public_skills(text, integer) to anon, authenticated;

